spring:
  application:
    name: config-server
  profiles:
    # git (git will be used), native(classpath configuration will be used)
    active: git
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          default-label: master
          force-pull: true
          timeout: 5
          uri: https://github.com/dev-ai-lab/bank-service-config.git
          # If private github is used, username-password, ssh etc
#          username: username
#          password: password
#        native:
#          search-location: "classpath:/config"
#           search-location: "file:///Users//bank//Documents//config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

encrypt:
  key: bankkey

server:
  port: 8071

logging:

  # Used by open telemetry %5p: log severity (info, error, debug). Trace-id and span-id generated by open telemetry will be inserted here.
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
